apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  annotations:
    gitlab.com/project-id: '61024755'
    gitlab.com/project-slug: 'brunocc.io/express-sample' # group_name/project_name
    #gitlab.com/instance: gitlab.internal.abcd # abcd, represents local instance used
spec:
  type: service
  lifecycle: production
  owner: bruno
