apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  annotations:
    gitlab.com/project-id: '60956168'
    gitlab.com/project-slug: 'experiments/nextjs-and-react-the-complete-guide' # group_name/project_name
    #gitlab.com/instance: gitlab.internal.abcd # abcd, represents local instance used
spec:
  type: service
  lifecycle: production
