apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  annotations:
    sonarqube.org/project-key: venuedevops_venuesh_dashboard_AYymQKA4QUfANSpXfyFk
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
